### ISSUE TITLE
The selfbot shutdown itself

### ISSUE THREAD

**Issue by infamouskoala** [kvnspncr/simple-selfbot#1]
The selfbot shutdown, Kevin got owned lmfao
the amount of cope on this dude is insane 
"I shut it down"
Get off my dick boy
![image](https://github.com/kvnspncr/simple-selfbot/assets/75808182/4aed4ccf-81a8-49d2-8049-b5294db71a23)
![image](https://github.com/kvnspncr/simple-selfbot/assets/75808182/6313565b-4ad3-4a3c-9e82-06d61beac24e)

**Comment by chupacker** [comment]
![image](https://github.com/kvnspncr/simple-selfbot/assets/91909231/2b45f0f2-f3f4-47d2-afa8-50604561c696)

**Comment by ghost** [comment]
![image0-1-1-3](https://github.com/kvnspncr/simple-selfbot/assets/141975639/965c1a73-ee04-4997-8080-74eabc910c52)

**Comment by kvnspncr** [comment]
im not sure if you know how a selfbot works but um it doesnt execute commands from others anyways i shut it down myself, ill leave this issue open just for your embarrassment

**Comment by ghost** [comment]
kevin i genuinely like you

**Comment by dadevguy** [comment]
kevin my guy 'immbr' wanna make love with you comon bruv

**Comment by ghost** [comment]
hes so cool

**Comment by infamouskoala** [comment]
> im not sure if you know how a selfbot works but um it doesnt execute commands from others anyways i shut it down myself, ill leave this issue open just for your embarrassment

A SELFBOT WITH 10 COMMANDS LMFAO, BUDDY THE EMBARRASSMENT IS ALL YOURS YOU SUCH A ATTENTION WHORE U HAVE TO MAKE 12 DISCORD ACCOUNTS AND JOIN MY SERVER FOR A SINGLE STAR ON UR BELOW AVERAGE SELFBOT REPO LMFAO

**Comment by kvnspncr** [comment]
![image](https://github.com/kvnspncr/simple-selfbot/assets/145229015/829ab517-cce6-4540-be1e-f30e4ae8e128)
so he tried command injecting my bot by escaping the codeblock but the thing is he only escaped the codeblock and his text is treated like a message, maybe you should think twice before you talk shit LOL

**Comment by ghost** [comment]
kevin i will star ur selfbot

**Comment by kvnspncr** [comment]
> > im not sure if you know how a selfbot works but um it doesnt execute commands from others anyways i shut it down myself, ill leave this issue open just for your embarrassment
> 
> A SELFBOT WITH 10 COMMANDS LMFAO, BUDDY THE EMBARRASSMENT IS ALL YOURS YOU SUCH A ATTENTION WHORE U HAVE TO MAKE 12 DISCORD ACCOUNTS AND JOIN MY SERVER FOR A SINGLE STAR ON UR BELOW AVERAGE SELFBOT REPO LMFAO

its better than your malware and besides i didnt update the repo in days and probably wont even bother with updating the repo because pajeets like you dont deserve good code LOL

**Comment by infamouskoala** [comment]
> ![image](https://private-user-images.githubusercontent.com/145229015/296005323-829ab517-cce6-4540-be1e-f30e4ae8e128.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5OTU2NjYsIm5iZiI6MTcwNDk5NTM2NiwicGF0aCI6Ii8xNDUyMjkwMTUvMjk2MDA1MzIzLTgyOWFiNTE3LWNjZTYtNDU0MC1iZTFlLWYzMGU0YWU4ZTEyOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMVQxNzQ5MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MDc2NzA5MDNkNjNmNGNhOTEwMjZjOThlZjc2ZWZjMjgxNmY2NjBhNTU3ZjE0ZGZiODJhNzQ0NDQyZGJhYjdlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5vqc_7GHm2Smev8VaivNz0HiaXNPOOaZFo4S092xNZ4) so he tried command injecting my bot by escaping the codeblock but the thing is he only escaped the codeblock and his text is treated like a message, maybe you should think twice before you talk shit LOL

![image](https://github.com/kvnspncr/simple-selfbot/assets/75808182/40d35d7d-b3ab-4237-8a8b-d38628808c2f)
who's the one talking?

**Comment by dadevguy** [comment]
kevin 'immrb' wanna marry you shall i do the arrangements?

**Comment by kvnspncr** [comment]
> > ![image](https://private-user-images.githubusercontent.com/145229015/296005323-829ab517-cce6-4540-be1e-f30e4ae8e128.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5OTU2NjYsIm5iZiI6MTcwNDk5NTM2NiwicGF0aCI6Ii8xNDUyMjkwMTUvMjk2MDA1MzIzLTgyOWFiNTE3LWNjZTYtNDU0MC1iZTFlLWYzMGU0YWU4ZTEyOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMVQxNzQ5MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MDc2NzA5MDNkNjNmNGNhOTEwMjZjOThlZjc2ZWZjMjgxNmY2NjBhNTU3ZjE0ZGZiODJhNzQ0NDQyZGJhYjdlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5vqc_7GHm2Smev8VaivNz0HiaXNPOOaZFo4S092xNZ4) so he tried command injecting my bot by escaping the codeblock but the thing is he only escaped the codeblock and his text is treated like a message, maybe you should think twice before you talk shit LOL
> 
> ![image](https://private-user-images.githubusercontent.com/75808182/296005916-40d35d7d-b3ab-4237-8a8b-d38628808c2f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5OTU3MDcsIm5iZiI6MTcwNDk5NTQwNywicGF0aCI6Ii83NTgwODE4Mi8yOTYwMDU5MTYtNDBkMzVkN2QtYjNhYi00MjM3LThhOGItZDM4NjI4ODA4YzJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDE3NTAwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjY2EyZjUzYWVkMmQ3YmEwMjUwOTM3M2JkMmIxZWFkZTBiNzc0ODZmMjc2NjMyNDgyZDU2YzNmMDAwOWFiMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.luNNt4psMWuWYzWanTgcM8fmlrOR8IwvEEOzq1t4644) who's the one talking?

i didnt pretend to command inject your shitty bot i just pointed out that you can escape the codeblock and ping other people and you applied that to my selfbot hahahaha

**Comment by infamouskoala** [comment]
proves my point of u riding ma cock for some attention lmao, go outside and play with ur friends kid its almost time
![image](https://github.com/kvnspncr/simple-selfbot/assets/75808182/d053adc2-34b8-4b4e-af73-a49a38b74afe)
